- name: Run Frontend
  docker_container:
    name: frontend
    image: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}/tp-devops-frontend:latest"
    pull: true
    networks:
      - name: app-network
    state: started
    restart_policy: always