- name: Run Frontend
  docker_container:
    name: frontend
    image: malocklion/tp-devops-frontend:latest
    pull: true
    networks:
      - name: app-network
    state: started
    restart_policy: always