- name: Run Database
  docker_container:
    name: database
    image: malocklion/tp-devops-database
    networks:
      - name: app-network
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd

