name: CI/CD Takima

on:
  workflow_run:
    workflows: ["CI devops 2025"] 
    types:
      - completed
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml \
          -u ${{ secrets.SERVER_USER }} \
          --private-key ~/.ssh/id_rsa \
          -e "dockerhub_user=${{ secrets.DOCKERHUB_USERNAME }}" 